### ISSUE TITLE
Build errors: #error "double and long double are the same size but LDBL_EQ_DBL is not defined", unknown type name '__ieee_ext_field_type' ...etc

### ISSUE THREAD

**Issue by Phi-Ho** [altera-opensource/intel-socfpga-hwlib#1]
Happy New Year

Please find appended below the errors in a failed build of intel-socfpga-hwlib

Please advise how to resolve these errors.

Regards,

phiho

---------------------------------------------------- Appended error messages ----------------------------------------
arm-eabi-gcc -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/ -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/targ-include -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/arm -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/libnosys -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/libgloss/arm    -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"3.1.0\" -DPACKAGE_STRING=\"newlib\ 3.1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -I. -I../../../../../newlib/libc/stdlib -fno-builtin -D__NO_SYSCALLS__ -D_COMPILING_NEWLIB -DHAVE_INIT_FINI      -g -O2 -c -o lib_a-gdtoa-gethex.o `test -f 'gdtoa-gethex.c' || echo '../../../../../newlib/libc/stdlib/'`gdtoa-gethex.c
arm-eabi-gcc -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/ -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/targ-include -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/arm -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/libnosys -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/libgloss/arm    -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"3.1.0\" -DPACKAGE_STRING=\"newlib\ 3.1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -I. -I../../../../../newlib/libc/stdlib -fno-builtin -D__NO_SYSCALLS__ -D_COMPILING_NEWLIB -DHAVE_INIT_FINI      -g -O2 -c -o lib_a-gdtoa-hexnan.o `test -f 'gdtoa-hexnan.c' || echo '../../../../../newlib/libc/stdlib/'`gdtoa-hexnan.c
arm-eabi-gcc -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/ -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/targ-include -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/arm -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/libnosys -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/libgloss/arm    -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"3.1.0\" -DPACKAGE_STRING=\"newlib\ 3.1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -I. -I../../../../../newlib/libc/stdlib -fno-builtin -D__NO_SYSCALLS__ -D_COMPILING_NEWLIB -DHAVE_INIT_FINI      -g -O2 -c -o lib_a-getenv.o `test -f 'getenv.c' || echo '../../../../../newlib/libc/stdlib/'`getenv.c
In file included from ../../../../../newlib/libc/stdlib/mprec.h:29:0,
                 from ../../../../../newlib/libc/stdlib/dtoa.c:33:
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:152:2: error: #error "double and long double are the same size but LDBL_EQ_DBL is not defined"
 #error "double and long double are the same size but LDBL_EQ_DBL is not defined"
  ^~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:195:3: error: unknown type name '__ieee_ext_field_type'
   __ieee_ext_field_type  ext_fracl : EXT_FRACLBITS;
   ^~~~~~~~~~~~~~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:195:38: error: 'EXT_FRACLBITS' undeclared here (not in a function); did you mean 'EXT_FRACBITS'?
   __ieee_ext_field_type  ext_fracl : EXT_FRACLBITS;
                                      ^~~~~~~~~~~~~
                                      EXT_FRACBITS
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:195:26: error: bit-field 'ext_fracl' width not an integer constant
   __ieee_ext_field_type  ext_fracl : EXT_FRACLBITS;
                          ^~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:196:3: error: unknown type name '__ieee_ext_field_type'
   __ieee_ext_field_type  ext_frach : EXT_FRACHBITS;
   ^~~~~~~~~~~~~~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:196:38: error: 'EXT_FRACHBITS' undeclared here (not in a function); did you mean 'EXT_FRACLBITS'?
   __ieee_ext_field_type  ext_frach : EXT_FRACHBITS;
                                      ^~~~~~~~~~~~~
                                      EXT_FRACLBITS
arm-eabi-gcc -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/ -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/targ-include -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/arm -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/libnosys -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/libgloss/arm    -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"3.1.0\" -DPACKAGE_STRING=\"newlib\ 3.1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -I. -I../../../../../newlib/libc/stdlib -fno-builtin -D__NO_SYSCALLS__ -D_COMPILING_NEWLIB -DHAVE_INIT_FINI      -g -O2 -c -o lib_a-getenv_r.o `test -f 'getenv_r.c' || echo '../../../../../newlib/libc/stdlib/'`getenv_r.c
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:196:26: error: bit-field 'ext_frach' width not an integer constant
   __ieee_ext_field_type  ext_frach : EXT_FRACHBITS;
                          ^~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:197:3: error: unknown type name '__ieee_ext_field_type'
   __ieee_ext_field_type  ext_exp   : EXT_EXPBITS;
   ^~~~~~~~~~~~~~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:197:38: error: 'EXT_EXPBITS' undeclared here (not in a function); did you mean 'EXT_EXP_BIAS'?
   __ieee_ext_field_type  ext_exp   : EXT_EXPBITS;
                                      ^~~~~~~~~~~
                                      EXT_EXP_BIAS
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:197:26: error: bit-field 'ext_exp' width not an integer constant
   __ieee_ext_field_type  ext_exp   : EXT_EXPBITS;
                          ^~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:198:3: error: unknown type name '__ieee_ext_field_type'
   __ieee_ext_field_type  ext_sign  : 1;
   ^~~~~~~~~~~~~~~~~~~~~
arm-eabi-gcc -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/ -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/targ-include -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/arm -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/libnosys -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/libgloss/arm    -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"3.1.0\" -DPACKAGE_STRING=\"newlib\ 3.1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -I. -I../../../../../newlib/libc/stdlib -fno-builtin -D__NO_SYSCALLS__ -D_COMPILING_NEWLIB -DHAVE_INIT_FINI      -g -O2 -c -o lib_a-imaxabs.o `test -f 'imaxabs.c' || echo '../../../../../newlib/libc/stdlib/'`imaxabs.c
arm-eabi-gcc -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/ -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/targ-include -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/arm -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/libnosys -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/libgloss/arm    -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"3.1.0\" -DPACKAGE_STRING=\"newlib\ 3.1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -I. -I../../../../../newlib/libc/stdlib -fno-builtin -D__NO_SYSCALLS__ -D_COMPILING_NEWLIB -DHAVE_INIT_FINI      -g -O2 -c -o lib_a-imaxdiv.o `test -f 'imaxdiv.c' || echo '../../../../../newlib/libc/stdlib/'`imaxdiv.c
In file included from ../../../../../newlib/libc/stdlib/mprec.h:29:0,
                 from ../../../../../newlib/libc/stdlib/gdtoa-gethex.c:36:
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:152:2: error: #error "double and long double are the same size but LDBL_EQ_DBL is not defined"
 #error "double and long double are the same size but LDBL_EQ_DBL is not defined"
  ^~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:195:3: error: unknown type name '__ieee_ext_field_type'
   __ieee_ext_field_type  ext_fracl : EXT_FRACLBITS;
   ^~~~~~~~~~~~~~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:195:38: error: 'EXT_FRACLBITS' undeclared here (not in a function); did you mean 'EXT_FRACBITS'?
   __ieee_ext_field_type  ext_fracl : EXT_FRACLBITS;
                                      ^~~~~~~~~~~~~
                                      EXT_FRACBITS
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:195:26: error: bit-field 'ext_fracl' width not an integer constant
   __ieee_ext_field_type  ext_fracl : EXT_FRACLBITS;
                          ^~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:196:3: error: unknown type name '__ieee_ext_field_type'
   __ieee_ext_field_type  ext_frach : EXT_FRACHBITS;
   ^~~~~~~~~~~~~~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:196:38: error: 'EXT_FRACHBITS' undeclared here (not in a function); did you mean 'EXT_FRACLBITS'?
   __ieee_ext_field_type  ext_frach : EXT_FRACHBITS;
                                      ^~~~~~~~~~~~~
                                      EXT_FRACLBITS
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:196:26: error: bit-field 'ext_frach' width not an integer constant
   __ieee_ext_field_type  ext_frach : EXT_FRACHBITS;
                          ^~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:197:3: error: unknown type name '__ieee_ext_field_type'
   __ieee_ext_field_type  ext_exp   : EXT_EXPBITS;
   ^~~~~~~~~~~~~~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:197:38: error: 'EXT_EXPBITS' undeclared here (not in a function); did you mean 'EXT_EXP_BIAS'?
   __ieee_ext_field_type  ext_exp   : EXT_EXPBITS;
                                      ^~~~~~~~~~~
                                      EXT_EXP_BIAS
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:197:26: error: bit-field 'ext_exp' width not an integer constant
   __ieee_ext_field_type  ext_exp   : EXT_EXPBITS;
                          ^~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:198:3: error: unknown type name '__ieee_ext_field_type'
   __ieee_ext_field_type  ext_sign  : 1;
   ^~~~~~~~~~~~~~~~~~~~~
arm-eabi-gcc -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/ -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/targ-include -isystem /G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include -B/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/arm -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/libgloss/libnosys -L/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/libgloss/arm    -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"3.1.0\" -DPACKAGE_STRING=\"newlib\ 3.1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -I. -I../../../../../newlib/libc/stdlib -fno-builtin -D__NO_SYSCALLS__ -D_COMPILING_NEWLIB -DHAVE_INIT_FINI      -g -O2 -c -o lib_a-itoa.o `test -f 'itoa.c' || echo '../../../../../newlib/libc/stdlib/'`itoa.c
In file included from ../../../../../newlib/libc/stdlib/mprec.h:29:0,
                 from ../../../../../newlib/libc/stdlib/gdtoa-hexnan.c:43:
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:152:2: error: #error "double and long double are the same size but LDBL_EQ_DBL is not defined"
 #error "double and long double are the same size but LDBL_EQ_DBL is not defined"
  ^~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:195:3: error: unknown type name '__ieee_ext_field_type'
   __ieee_ext_field_type  ext_fracl : EXT_FRACLBITS;
   ^~~~~~~~~~~~~~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:195:38: error: 'EXT_FRACLBITS' undeclared here (not in a function); did you mean 'EXT_FRACBITS'?
   __ieee_ext_field_type  ext_fracl : EXT_FRACLBITS;
                                      ^~~~~~~~~~~~~
                                      EXT_FRACBITS
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:195:26: error: bit-field 'ext_fracl' width not an integer constant
   __ieee_ext_field_type  ext_fracl : EXT_FRACLBITS;
                          ^~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:196:3: error: unknown type name '__ieee_ext_field_type'
   __ieee_ext_field_type  ext_frach : EXT_FRACHBITS;
   ^~~~~~~~~~~~~~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:196:38: error: 'EXT_FRACHBITS' undeclared here (not in a function); did you mean 'EXT_FRACLBITS'?
   __ieee_ext_field_type  ext_frach : EXT_FRACHBITS;
                                      ^~~~~~~~~~~~~
                                      EXT_FRACLBITS
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:196:26: error: bit-field 'ext_frach' width not an integer constant
   __ieee_ext_field_type  ext_frach : EXT_FRACHBITS;
                          ^~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:197:3: error: unknown type name '__ieee_ext_field_type'
   __ieee_ext_field_type  ext_exp   : EXT_EXPBITS;
   ^~~~~~~~~~~~~~~~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:197:38: error: 'EXT_EXPBITS' undeclared here (not in a function); did you mean 'EXT_EXP_BIAS'?
   __ieee_ext_field_type  ext_exp   : EXT_EXPBITS;
                                      ^~~~~~~~~~~
                                      EXT_EXP_BIAS
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:197:26: error: bit-field 'ext_exp' width not an integer constant
   __ieee_ext_field_type  ext_exp   : EXT_EXPBITS;
                          ^~~~~~~
g:/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/newlib/libc/include/ieeefp.h:198:3: error: unknown type name '__ieee_ext_field_type'
   __ieee_ext_field_type  ext_sign  : 1;
   ^~~~~~~~~~~~~~~~~~~~~
make[5]: *** [lib_a-dtoa.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: *** [lib_a-gdtoa-gethex.o] Error 1
make[5]: *** [lib_a-gdtoa-hexnan.o] Error 1
make[5]: Leaving directory `/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/libc/stdlib'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib/libc'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build/arm-eabi/newlib'
make[1]: *** [all-target-newlib] Error 2
make[1]: Leaving directory `/G/intel/FPGA/Lite/20.1.1.720/embedded/intel-socfpga-hwlib/tools/newlib-cygwin/build'
make: *** [all] Error 2

**Comment by ngbk1993** [comment]
I hit into this issue before, this is due to the compiler not able to recognize the line ending for windows. 
When you install git for windows, make sure you choose "checkout as-is, commit unix-style line endings"
![image](https://user-images.githubusercontent.com/17378972/104619231-9816a180-56c8-11eb-9e0f-0359100f6945.png)

**Comment by Phi-Ho** [comment]
Hello,

I followed your advice, reinstalling git with "Checkout as is, commit Unix-style line ending" and "install_linaro.sh" for EDS 20.1 successfully completed. Thank you so much.

I am wondering if you have encountered the problem with JTAG problem when using FPGA Monitor to connect to the board:

Could not query JTAG Instance IDs.
Please ensure the FPGA has been configured using the correct .sof file.

I am using DE10-Nano board. Your help is much appreciated.

Regards,

phiho

**Comment by ngbk1993** [comment]
Hi Phi-Ho,

Hrmm, I never hit into that issue before, maybe you can try ask in this forum?
https://community.intel.com/t5/Programmable-Devices/bd-p/programmable-devices

Quick question, did you configure the FPGA with cycloneV sof? 
maybe you can refer the guide from https://rocketboards.org/

**Comment by Phi-Ho** [comment]
Hi,

Thank you very much for your reply.

I did try both Rocketboard and Intel Community before for the problems
related to the question you helped me with originally with no success. Your
help is truly appreciated.

I will try again with the question about JTAG Debugging on Intel Community.

Best regards,

phiho

**Comment by ngbk1993** [comment]
Hi Phi-Ho,

No problem. I think you should close this issue as the steps solved your Build error issue.

Your second issue is more to FPGA side, I think Intel Community and Rocketboard Community have more expert there to help you, can share me the link where you ask the question about JTAG Debugging? I would like to know the solution as well.

**Comment by Phi-Ho** [comment]
Hi,

I am closing this thread now and how should I share with you the solution for the JTAG Debugging issue, IF there is any help coming from those community boards?

Regards,

phiho

**Comment by ngbk1993** [comment]
Hi Phi-Ho,

Maybe you can drop me an email at ngbk1993@hotmail.com
Thanks and have a nice day :)

**Comment by Phi-Ho** [comment]
Hi,

Yes, for sure you will be informed when I get a solution.

Cheers,

phiho
